/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdvertisementRouteImport } from './routes/advertisement'
import { Route as CertificatesRouteImport } from './routes/certificates'
import { Route as ChairmanMessageRouteImport } from './routes/chairman-message'
import { Route as ClientsRouteImport } from './routes/clients'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CurrentOpeningRouteImport } from './routes/current-opening'
import { Route as HireTalentRouteImport } from './routes/hire-talent'
import { Route as IntroductionRouteImport } from './routes/introduction'
import { Route as MissionVisionRouteImport } from './routes/mission-vision'
import { Route as OrganizationChartRouteImport } from './routes/organization-chart'
import { Route as ProcessRouteImport } from './routes/process'
import { Route as ServiceCategoriesRouteImport } from './routes/service-categories'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as SisterConcernsRouteImport } from './routes/sister-concerns'
import { Route as WhatWeDoRouteImport } from './routes/what-we-do'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvertisementRoute = AdvertisementRouteImport.update({
  id: '/advertisement',
  path: '/advertisement',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificatesRoute = CertificatesRouteImport.update({
  id: '/certificates',
  path: '/certificates',
  getParentRoute: () => rootRouteImport,
} as any)
const ChairmanMessageRoute = ChairmanMessageRouteImport.update({
  id: '/chairman-message',
  path: '/chairman-message',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsRoute = ClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CurrentOpeningRoute = CurrentOpeningRouteImport.update({
  id: '/current-opening',
  path: '/current-opening',
  getParentRoute: () => rootRouteImport,
} as any)
const HireTalentRoute = HireTalentRouteImport.update({
  id: '/hire-talent',
  path: '/hire-talent',
  getParentRoute: () => rootRouteImport,
} as any)
const IntroductionRoute = IntroductionRouteImport.update({
  id: '/introduction',
  path: '/introduction',
  getParentRoute: () => rootRouteImport,
} as any)
const MissionVisionRoute = MissionVisionRouteImport.update({
  id: '/mission-vision',
  path: '/mission-vision',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationChartRoute = OrganizationChartRouteImport.update({
  id: '/organization-chart',
  path: '/organization-chart',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcessRoute = ProcessRouteImport.update({
  id: '/process',
  path: '/process',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceCategoriesRoute = ServiceCategoriesRouteImport.update({
  id: '/service-categories',
  path: '/service-categories',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const SisterConcernsRoute = SisterConcernsRouteImport.update({
  id: '/sister-concerns',
  path: '/sister-concerns',
  getParentRoute: () => rootRouteImport,
} as any)
const WhatWeDoRoute = WhatWeDoRouteImport.update({
  id: '/what-we-do',
  path: '/what-we-do',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/advertisement': typeof AdvertisementRoute
  '/certificates': typeof CertificatesRoute
  '/chairman-message': typeof ChairmanMessageRoute
  '/clients': typeof ClientsRoute
  '/contact': typeof ContactRoute
  '/current-opening': typeof CurrentOpeningRoute
  '/hire-talent': typeof HireTalentRoute
  '/introduction': typeof IntroductionRoute
  '/mission-vision': typeof MissionVisionRoute
  '/organization-chart': typeof OrganizationChartRoute
  '/process': typeof ProcessRoute
  '/service-categories': typeof ServiceCategoriesRoute
  '/services': typeof ServicesRoute
  '/sister-concerns': typeof SisterConcernsRoute
  '/what-we-do': typeof WhatWeDoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/advertisement': typeof AdvertisementRoute
  '/certificates': typeof CertificatesRoute
  '/chairman-message': typeof ChairmanMessageRoute
  '/clients': typeof ClientsRoute
  '/contact': typeof ContactRoute
  '/current-opening': typeof CurrentOpeningRoute
  '/hire-talent': typeof HireTalentRoute
  '/introduction': typeof IntroductionRoute
  '/mission-vision': typeof MissionVisionRoute
  '/organization-chart': typeof OrganizationChartRoute
  '/process': typeof ProcessRoute
  '/service-categories': typeof ServiceCategoriesRoute
  '/services': typeof ServicesRoute
  '/sister-concerns': typeof SisterConcernsRoute
  '/what-we-do': typeof WhatWeDoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/advertisement': typeof AdvertisementRoute
  '/certificates': typeof CertificatesRoute
  '/chairman-message': typeof ChairmanMessageRoute
  '/clients': typeof ClientsRoute
  '/contact': typeof ContactRoute
  '/current-opening': typeof CurrentOpeningRoute
  '/hire-talent': typeof HireTalentRoute
  '/introduction': typeof IntroductionRoute
  '/mission-vision': typeof MissionVisionRoute
  '/organization-chart': typeof OrganizationChartRoute
  '/process': typeof ProcessRoute
  '/service-categories': typeof ServiceCategoriesRoute
  '/services': typeof ServicesRoute
  '/sister-concerns': typeof SisterConcernsRoute
  '/what-we-do': typeof WhatWeDoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/advertisement'
    | '/certificates'
    | '/chairman-message'
    | '/clients'
    | '/contact'
    | '/current-opening'
    | '/hire-talent'
    | '/introduction'
    | '/mission-vision'
    | '/organization-chart'
    | '/process'
    | '/service-categories'
    | '/services'
    | '/sister-concerns'
    | '/what-we-do'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/advertisement'
    | '/certificates'
    | '/chairman-message'
    | '/clients'
    | '/contact'
    | '/current-opening'
    | '/hire-talent'
    | '/introduction'
    | '/mission-vision'
    | '/organization-chart'
    | '/process'
    | '/service-categories'
    | '/services'
    | '/sister-concerns'
    | '/what-we-do'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/advertisement'
    | '/certificates'
    | '/chairman-message'
    | '/clients'
    | '/contact'
    | '/current-opening'
    | '/hire-talent'
    | '/introduction'
    | '/mission-vision'
    | '/organization-chart'
    | '/process'
    | '/service-categories'
    | '/services'
    | '/sister-concerns'
    | '/what-we-do'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdvertisementRoute: typeof AdvertisementRoute
  CertificatesRoute: typeof CertificatesRoute
  ChairmanMessageRoute: typeof ChairmanMessageRoute
  ClientsRoute: typeof ClientsRoute
  ContactRoute: typeof ContactRoute
  CurrentOpeningRoute: typeof CurrentOpeningRoute
  HireTalentRoute: typeof HireTalentRoute
  IntroductionRoute: typeof IntroductionRoute
  MissionVisionRoute: typeof MissionVisionRoute
  OrganizationChartRoute: typeof OrganizationChartRoute
  ProcessRoute: typeof ProcessRoute
  ServiceCategoriesRoute: typeof ServiceCategoriesRoute
  ServicesRoute: typeof ServicesRoute
  SisterConcernsRoute: typeof SisterConcernsRoute
  WhatWeDoRoute: typeof WhatWeDoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advertisement': {
      id: '/advertisement'
      path: '/advertisement'
      fullPath: '/advertisement'
      preLoaderRoute: typeof AdvertisementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certificates': {
      id: '/certificates'
      path: '/certificates'
      fullPath: '/certificates'
      preLoaderRoute: typeof CertificatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chairman-message': {
      id: '/chairman-message'
      path: '/chairman-message'
      fullPath: '/chairman-message'
      preLoaderRoute: typeof ChairmanMessageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients': {
      id: '/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof ClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/current-opening': {
      id: '/current-opening'
      path: '/current-opening'
      fullPath: '/current-opening'
      preLoaderRoute: typeof CurrentOpeningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hire-talent': {
      id: '/hire-talent'
      path: '/hire-talent'
      fullPath: '/hire-talent'
      preLoaderRoute: typeof HireTalentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/introduction': {
      id: '/introduction'
      path: '/introduction'
      fullPath: '/introduction'
      preLoaderRoute: typeof IntroductionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mission-vision': {
      id: '/mission-vision'
      path: '/mission-vision'
      fullPath: '/mission-vision'
      preLoaderRoute: typeof MissionVisionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organization-chart': {
      id: '/organization-chart'
      path: '/organization-chart'
      fullPath: '/organization-chart'
      preLoaderRoute: typeof OrganizationChartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/process': {
      id: '/process'
      path: '/process'
      fullPath: '/process'
      preLoaderRoute: typeof ProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service-categories': {
      id: '/service-categories'
      path: '/service-categories'
      fullPath: '/service-categories'
      preLoaderRoute: typeof ServiceCategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sister-concerns': {
      id: '/sister-concerns'
      path: '/sister-concerns'
      fullPath: '/sister-concerns'
      preLoaderRoute: typeof SisterConcernsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/what-we-do': {
      id: '/what-we-do'
      path: '/what-we-do'
      fullPath: '/what-we-do'
      preLoaderRoute: typeof WhatWeDoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdvertisementRoute: AdvertisementRoute,
  CertificatesRoute: CertificatesRoute,
  ChairmanMessageRoute: ChairmanMessageRoute,
  ClientsRoute: ClientsRoute,
  ContactRoute: ContactRoute,
  CurrentOpeningRoute: CurrentOpeningRoute,
  HireTalentRoute: HireTalentRoute,
  IntroductionRoute: IntroductionRoute,
  MissionVisionRoute: MissionVisionRoute,
  OrganizationChartRoute: OrganizationChartRoute,
  ProcessRoute: ProcessRoute,
  ServiceCategoriesRoute: ServiceCategoriesRoute,
  ServicesRoute: ServicesRoute,
  SisterConcernsRoute: SisterConcernsRoute,
  WhatWeDoRoute: WhatWeDoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
